#!/usr/bin/env bash
# Usage: ./gen_clicodes.sh [syn1,syn2 ...]

FILE="include/constants.h"
MARKER="/* CLI CODES  - @generated by scripts/gen_clicodes.sh */"
ENDMARKER="/* */"

if [[ ! -f "$FILE" ]]; then
    echo "Error: $FILE not found." >&2
    exit 1
fi

mapfile -t raw_entries < <(
    awk '
        /_cmds\[\]/ && /=/ {
            # Extract variable name (e.g., compiler_cmds)
            split($0, left, "=")
            varname = left[1]
            gsub(/^[ \t*]+|[ \t*]+$/, "", varname)
            gsub(/^.*[ \t]/, "", varname)
            gsub(/\[.*$/, "", varname)
            prefix = toupper(substr(varname, 1, 1))

            start = index($0, "{")
            end   = index($0, "}")
            if (start == 0 || end == 0) next
            content = substr($0, start+1, end-start-1)

            split(content, items, ",")
            for (i in items) {
                gsub(/^[ \t"]+|[ \t"]+$/, "", items[i])
                if (items[i] != "")
                    print prefix, items[i]
            }
        }
    ' "$FILE"
)

if [[ ${#raw_entries[@]} -eq 0 ]]; then
    echo "Error: No '_cmds[]' arrays found in $FILE" >&2
    exit 1
fi

declare -A group_of_cmd
group_idx=0
for arg in "$@"; do
    IFS=',' read -ra synonyms <<<"$arg"
    for syn in "${synonyms[@]}"; do
        group_of_cmd["$syn"]=$group_idx
    done
    ((group_idx++))
done

transform() {
    local cmd="$1"
    local stripped="${cmd##-}"
    local underscored="${stripped//-/_}"
    echo "${underscored^^}"
}

code_lines=()
prev_group=-1
counter=-1

for entry in "${raw_entries[@]}"; do
    prefix="${entry%% *}"
    cmd="${entry#* }"

    cur_group=-1
    if [[ -v group_of_cmd["$cmd"] ]]; then
        cur_group="${group_of_cmd[$cmd]}"
    fi

    if [[ $counter -eq -1 ]]; then
        ((counter++))
    else
        if [[ $cur_group -ne -1 && $cur_group -eq $prev_group ]]; then
            :
        else
            ((counter++))
        fi
    fi
    prev_group=$cur_group

    name_part=$(transform "$cmd")
    const_name="${prefix}CODE_${name_part}"
    code_lines+=("int ${const_name} = ${counter};")
done

start_ln=$(grep -n -F "$MARKER" "$FILE" | head -1 | cut -d: -f1)
if [[ -z "$start_ln" ]]; then
    echo "Error: Start marker not found in $FILE" >&2
    exit 1
fi

end_rel=$(tail -n +$((start_ln + 1)) "$FILE" | grep -n -F "$ENDMARKER" | head -1 | cut -d: -f1)
if [[ -z "$end_rel" ]]; then
    echo "Error: End marker not found after start marker" >&2
    exit 1
fi
end_ln=$((start_ln + end_rel))

tmpfile=$(mktemp)
{
    head -n "$start_ln" "$FILE"
    for line in "${code_lines[@]}"; do
        printf '%s\n' "$line"
    done
    tail -n "+$end_ln" "$FILE"
} >"$tmpfile"

mv "$tmpfile" "$FILE"
echo "Updated $FILE successfully." >&2
