#ifndef CONSTANTS_H
#define CONSTANTS_H

/* CLI */

#include <stdio.h>
const char* compiler_cmds[] = {"build", "check", "link"};
const char* debug_cmds[] = {"-g", "-debug", "-ptok"};

typedef union {
    const char** compiler;
    const char** debug;
} cmds;

inline cmds* init_cmds(cmds* c) {
    c->compiler = NULL;
    c->debug = NULL;
    return c;
}

inline cmds update_cmds(int i) {
    cmds* c = NULL;
    init_cmds(c);
    switch (i) {
        case 1:
            c->compiler = compiler_cmds;
            return *c;
        case 2:
            c->debug = debug_cmds;
            return *c;
        default:
            fprintf(stderr,
                    "constants::update_cmds: Given %d (index) is not valid", i);
            return *c;
    }
}

/* CLI CODES  - @generated by scripts/gen_clicodes.sh */
int CCODE_BUILD = 0;
int CCODE_CHECK = 1;
int CCODE_LINK = 2;
int DCODE_G = 3;
int DCODE_DEBUG = 3;
int DCODE_PTOK = 4;
/* */

#endif  // !CONSTANTS_H
